version: '3'
services:
  server:
    build: ./server
    command: bash -c "npm install && npm run build-ts && npm run dev"
    env_file: server.env
    ports:
      - '4200:4200'
    working_dir: /root/server
    volumes:
      - ./server:/root/server:cached
  users:
    build: ./users
    command: sh -c "npm install && npm run start"
    env_file: server.env # needs its own file :/
    ports:
      - '9876:9876'
    working_dir: /root/users
    volumes:
      - ./users:/root/users:cached
  client:
    build: ./client
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 3000"
    ports:
      - '3000:3000'
    working_dir: /root/client
    volumes:
      - ./client:/root/client:cached
    # links:
    #   - users_db
  users_db:
    build: ./db/users
    ports:
      - '27017:27017'
    volumes:
      - ./db/users/init-users-db.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/users/users_db:/data/db
